name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v3

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Init
      run: terraform init
      working-directory: modules/ec2

    - name: Plan
      run: terraform plan -var="do_token=${{ secrets.DO_TOKEN }}"
      working-directory: modules/ec2

    # Add to .github/workflows/blank.yml after Apply step
    - name: Destroy (on destroy branch)
      if: github.ref == 'refs/heads/destroy'
      run: terraform destroy -auto-approve -var="do_token=${{ secrets.DO_TOKEN }}"
      working-directory: modules/ec2
