name: Deploy Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # Add to .github/workflows/blank.yml after Apply step
    - name: Destroy (on destroy branch)
      run: terraform destroy -auto-approve -var="do_token=${{ secrets.DO_TOKEN }}"
      working-directory: modules/ec2
